name: mtgjson_converter_dart
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/j7126/mtgjson_converter_dart

environment:
  sdk: ^3.2.3

dependencies:
  json_annotation: ^4.8.1
  string_normalizer: ^0.2.2
  collection: ^1.18.0
  path: ^1.8.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2

dev_dependencies:
  lints: ^2.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
